{% set name = "msmhelper" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/msmhelper-{{ version }}.tar.gz
  sha256: 2bcb664fe677ef31a499a679078b2006096661013e7077d1cce91a2a2e92a893

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - decorit
    - numba
    - numpy
    - pandas
    - python >=3.6
    - scipy

test:
  imports:
    - msmhelper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/moldyn/msmhelper
  summary: Toolbox for Markov State Modeling of Protein Dynamics
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://moldyn.github.io/msmhelper/

extra:
  recipe-maintainers:
    - braniii
