{% set name = "msmhelper" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/msmhelper-{{ version }}.tar.gz
  sha256: 3c442aa49034c1d9ef6c117605c32b161192c0c679f57cdb6ca990bcae7f83a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - decorit
    - numba
    - numpy
    - pandas
    - prettypyplot
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - msmhelper
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/moldyn/msmhelper
  summary: Toolbox for Markov State Modeling of Protein Dynamics
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://moldyn.github.io/msmhelper/

extra:
  recipe-maintainers:
    - braniii
