{% set name = "msmhelper" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/msmhelper-{{ version }}.tar.gz
  sha256: 32bc07764a866f510d1563e082790883b46008caedfe53b240c5e2ce3a9e8800

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - decorit
    - numba
    - numpy
    - pandas
    - prettypyplot
    - python >=3.7
    - scipy

test:
  imports:
    - msmhelper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/moldyn/msmhelper
  summary: Toolbox for Markov State Modeling of Protein Dynamics
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://moldyn.github.io/msmhelper/

extra:
  recipe-maintainers:
    - braniii
